-- Nexora V1.1 — administration + catalogue dynamique
-- À exécuter dans Supabase > SQL Editor.

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.catalog_items (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('formation','service','site')),
  slug text not null,
  title text,
  name text,
  full_name text,
  category text,
  level text,
  icon text,
  description text,
  bullets jsonb not null default '[]'::jsonb,
  price numeric(10,2),
  price_label text,
  status text,
  accent text,
  url text,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(type, slug)
);

alter table public.admin_users enable row level security;
alter table public.catalog_items enable row level security;

drop policy if exists "admin can see own admin record" on public.admin_users;
create policy "admin can see own admin record" on public.admin_users
  for select to authenticated using (user_id = auth.uid());

drop policy if exists "public can read active catalog" on public.catalog_items;
create policy "public can read active catalog" on public.catalog_items
  for select to anon, authenticated using (active = true);

drop policy if exists "admins can manage catalog" on public.catalog_items;
create policy "admins can manage catalog" on public.catalog_items
  for all to authenticated
  using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()))
  with check (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));

-- Compte administrateur Nexora principal.
-- Ce compte est automatiquement ajouté à admin_users à sa création.
-- Il est également ajouté immédiatement s'il existe déjà.

create or replace function public.nexora_auto_admin()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if lower(coalesce(new.email, '')) = lower('nexora.plateforme@gmail.com') then
    insert into public.admin_users (user_id)
    values (new.id)
    on conflict (user_id) do nothing;
  end if;
  return new;
end;
$$;

drop trigger if exists nexora_auto_admin_trigger on auth.users;
create trigger nexora_auto_admin_trigger
after insert on auth.users
for each row
execute function public.nexora_auto_admin();

insert into public.admin_users (user_id)
select id
from auth.users
where lower(email) = lower('nexora.plateforme@gmail.com')
on conflict (user_id) do nothing;

-- Ancienne méthode manuelle (inutile pour le compte ci-dessus) :
-- insert into public.admin_users (user_id) values ('TON-USER-UUID');

-- Données initiales (les pages utilisent ces données dès qu'elles existent).
insert into public.catalog_items (type, slug, title, category, level, icon, description, bullets, price, active, sort_order) values
('formation','fivem','Développement FiveM','Développement','Débutant → Avancé','🎮','Apprenez à construire des ressources FiveM propres, structurées et maintenables.', '["Structure d''une ressource","Lua, events et callbacks","NUI et interfaces","SQL et bases de données","Optimisation et bonnes pratiques"]',29.90,true,1),
('formation','gmod','Développement GMod','Développement','Débutant → Intermédiaire','⚙️','Créez vos propres systèmes et addons Garry''s Mod avec une méthode progressive.', '["Lua pour GMod","SWEP et entités","Interfaces Derma","Hooks et networking","Organisation d''un addon"]',24.90,true,2),
('formation','pc','Optimisation PC & jeux','Performance','Tous niveaux','🚀','Comprenez votre machine et optimisez Windows, vos jeux et votre environnement.', '["Diagnostic des performances","Windows et démarrage","GPU / CPU / RAM","Réglages en jeu","Méthode de benchmark"]',14.90,true,3),
('formation','python','Python de zéro','Programmation','Débutant','🐍','Découvrez Python et construisez vos premiers programmes de manière concrète.', '["Variables et conditions","Boucles et fonctions","Fichiers et modules","APIs et automatisation","Mini-projet final"]',19.90,true,4),
('formation','javascript','JavaScript moderne','Programmation','Débutant → Intermédiaire','✨','Les bases solides pour créer des interfaces et applications web modernes.', '["JavaScript moderne","DOM et événements","Asynchrone et APIs","Modules","Projet pratique"]',22.90,true,5),
('formation','web','Créer son site web','Web','Tous niveaux','🌐','Passez de l''idée à un site moderne, responsive et publiable en ligne.', '["HTML et CSS","Responsive design","UX de base","Déploiement","SEO essentiel"]',17.90,true,6)
on conflict (type,slug) do nothing;

insert into public.catalog_items (type, slug, title, icon, description, price_label, active, sort_order) values
('service','developpement-sur-mesure','Développement sur mesure','Code2','Création de scripts, systèmes et fonctionnalités adaptés à votre projet.','À partir de 49 €',true,1),
('service','creation-site-web','Création de site web','Globe','Sites vitrines, landing pages et plateformes modernes prêtes à évoluer.','À partir de 79 €',true,2),
('service','optimisation-pc-jeux','Optimisation PC & jeux','Gauge','Analyse et amélioration des performances de votre PC, jeu ou environnement.','À partir de 29 €',true,3),
('service','accompagnement-technique','Accompagnement technique','LifeBuoy','Aide au diagnostic, débogage et résolution de problèmes techniques.','À partir de 19 €',true,4),
('service','ui-design-web','UI / Design web','PenTool','Interfaces modernes et cohérentes pour donner une vraie identité à votre projet.','Sur devis',true,5),
('service','automatisation','Automatisation','Bot','Scripts et outils pour supprimer les tâches répétitives et gagner du temps.','Sur devis',true,6)
on conflict (type,slug) do nothing;

insert into public.catalog_items (type, slug, name, full_name, title, icon, description, status, accent, url, active, sort_order) values
('site','sen','S.E.N','Shinobi Era Nations','S.E.N','Globe2','Une expérience communautaire Naruto RP avec boutique, services et univers dédié.','Projet actif','Naruto','https://daily76.wixsite.com/sen-naruto-rp-1',true,1),
('site','echos-wl','Echos WL','Echos Whitelist','Echos WL','Globe2','Serveur GTA RP Whitelist avec une identité immersive, une économie et un univers communautaire.','Projet actif','GTA RP','https://daily76.wixsite.com/echos-wl',true,2),
('site','axion-shop','Axion Shop','Dev · Optimization · Vente','Axion Shop','Globe2','Boutique orientée développement, ressources, mapping et optimisation PC / jeux vidéo.','Projet actif','Digital','https://daily76.wixsite.com/axion-shop',true,3)
on conflict (type,slug) do nothing;
