-- Nexora V1.1 — administration + catalogue dynamique
-- À exécuter dans Supabase > SQL Editor.

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.catalog_items (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('formation','service','site')),
  slug text not null,
  title text,
  name text,
  full_name text,
  category text,
  level text,
  icon text,
  description text,
  bullets jsonb not null default '[]'::jsonb,
  price numeric(10,2),
  price_label text,
  status text,
  accent text,
  url text,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(type, slug)
);

alter table public.admin_users enable row level security;
alter table public.catalog_items enable row level security;

drop policy if exists "admin can see own admin record" on public.admin_users;
create policy "admin can see own admin record" on public.admin_users
  for select to authenticated using (user_id = auth.uid());

drop policy if exists "public can read active catalog" on public.catalog_items;
create policy "public can read active catalog" on public.catalog_items
  for select to anon, authenticated using (active = true);

drop policy if exists "admins can manage catalog" on public.catalog_items;
create policy "admins can manage catalog" on public.catalog_items
  for all to authenticated
  using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()))
  with check (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));

-- Données initiales (les pages utilisent ces données dès qu'elles existent).
insert into public.catalog_items (type, slug, title, category, level, icon, description, bullets, price, active, sort_order) values
('formation','fivem','Développement FiveM','Développement','Débutant → Avancé','🎮','Apprenez à construire des ressources FiveM propres, structurées et maintenables.', '["Structure d''une ressource","Lua, events et callbacks","NUI et interfaces","SQL et bases de données","Optimisation et bonnes pratiques"]',29.90,true,1),
('formation','gmod','Développement GMod','Développement','Débutant → Intermédiaire','⚙️','Créez vos propres systèmes et addons Garry''s Mod avec une méthode progressive.', '["Lua pour GMod","SWEP et entités","Interfaces Derma","Hooks et networking","Organisation d''un addon"]',24.90,true,2),
('formation','pc','Optimisation PC & jeux','Performance','Tous niveaux','🚀','Comprenez votre machine et optimisez Windows, vos jeux et votre environnement.', '["Diagnostic des performances","Windows et démarrage","GPU / CPU / RAM","Réglages en jeu","Méthode de benchmark"]',14.90,true,3),
('formation','python','Python de zéro','Programmation','Débutant','🐍','Découvrez Python et construisez vos premiers programmes de manière concrète.', '["Variables et conditions","Boucles et fonctions","Fichiers et modules","APIs et automatisation","Mini-projet final"]',19.90,true,4),
('formation','javascript','JavaScript moderne','Programmation','Débutant → Intermédiaire','✨','Les bases solides pour créer des interfaces et applications web modernes.', '["JavaScript moderne","DOM et événements","Asynchrone et APIs","Modules","Projet pratique"]',22.90,true,5),
('formation','web','Créer son site web','Web','Tous niveaux','🌐','Passez de l''idée à un site moderne, responsive et publiable en ligne.', '["HTML et CSS","Responsive design","UX de base","Déploiement","SEO essentiel"]',17.90,true,6)
on conflict (type,slug) do nothing;

insert into public.catalog_items (type, slug, title, icon, description, price_label, active, sort_order) values
('service','developpement-sur-mesure','Développement sur mesure','Code2','Création de scripts, systèmes et fonctionnalités adaptés à votre projet.','À partir de 49 €',true,1),
('service','creation-site-web','Création de site web','Globe','Sites vitrines, landing pages et plateformes modernes prêtes à évoluer.','À partir de 79 €',true,2),
('service','optimisation-pc-jeux','Optimisation PC & jeux','Gauge','Analyse et amélioration des performances de votre PC, jeu ou environnement.','À partir de 29 €',true,3),
('service','accompagnement-technique','Accompagnement technique','LifeBuoy','Aide au diagnostic, débogage et résolution de problèmes techniques.','À partir de 19 €',true,4),
('service','ui-design-web','UI / Design web','PenTool','Interfaces modernes et cohérentes pour donner une vraie identité à votre projet.','Sur devis',true,5),
('service','automatisation','Automatisation','Bot','Scripts et outils pour supprimer les tâches répétitives et gagner du temps.','Sur devis',true,6)
on conflict (type,slug) do nothing;

insert into public.catalog_items (type, slug, name, full_name, title, icon, description, status, accent, url, active, sort_order) values
('site','sen','S.E.N','Shinobi Era Nations','S.E.N','Globe2','Une expérience communautaire Naruto RP avec boutique, services et univers dédié.','Projet actif','Naruto','https://daily76.wixsite.com/sen-naruto-rp-1',true,1),
('site','echos-wl','Echos WL','Echos Whitelist','Echos WL','Globe2','Serveur GTA RP Whitelist avec une identité immersive, une économie et un univers communautaire.','Projet actif','GTA RP','https://daily76.wixsite.com/echos-wl',true,2),
('site','axion-shop','Axion Shop','Dev · Optimization · Vente','Axion Shop','Globe2','Boutique orientée développement, ressources, mapping et optimisation PC / jeux vidéo.','Projet actif','Digital','https://daily76.wixsite.com/axion-shop',true,3)
on conflict (type,slug) do nothing;

-- ============================================================
-- Nexora V1.3 — utilisateurs, demandes, messagerie et éditeur
-- ============================================================

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  provider text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contact_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  name text not null,
  email text not null,
  request_type text not null default 'Projet',
  budget text,
  subject text not null,
  message text not null,
  status text not null default 'new' check (status in ('new','in_progress','answered','closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.request_messages (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references public.contact_requests(id) on delete cascade,
  sender_id uuid references auth.users(id) on delete set null,
  sender_role text not null check (sender_role in ('user','admin')),
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.site_content (
  page_key text primary key,
  content jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.contact_requests enable row level security;
alter table public.request_messages enable row level security;
alter table public.site_content enable row level security;

drop policy if exists "users can see own profile" on public.profiles;
create policy "users can see own profile" on public.profiles for select to authenticated using (user_id=auth.uid());
drop policy if exists "admins can see profiles" on public.profiles;
create policy "admins can see profiles" on public.profiles for select to authenticated using (exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
drop policy if exists "users can update own profile" on public.profiles;
create policy "users can update own profile" on public.profiles for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists "admins can manage profiles" on public.profiles;
create policy "admins can manage profiles" on public.profiles for all to authenticated using(exists(select 1 from public.admin_users a where a.user_id=auth.uid())) with check(exists(select 1 from public.admin_users a where a.user_id=auth.uid()));

drop policy if exists "users can create own requests" on public.contact_requests;
create policy "users can create own requests" on public.contact_requests for insert to authenticated with check(user_id=auth.uid());
drop policy if exists "users can read own requests" on public.contact_requests;
create policy "users can read own requests" on public.contact_requests for select to authenticated using(user_id=auth.uid());
drop policy if exists "admins can manage requests" on public.contact_requests;
create policy "admins can manage requests" on public.contact_requests for all to authenticated using(exists(select 1 from public.admin_users a where a.user_id=auth.uid())) with check(exists(select 1 from public.admin_users a where a.user_id=auth.uid()));

drop policy if exists "users can read own request messages" on public.request_messages;
create policy "users can read own request messages" on public.request_messages for select to authenticated using(exists(select 1 from public.contact_requests r where r.id=request_id and r.user_id=auth.uid()));
drop policy if exists "admins can manage request messages" on public.request_messages;
create policy "admins can manage request messages" on public.request_messages for all to authenticated using(exists(select 1 from public.admin_users a where a.user_id=auth.uid())) with check(exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
drop policy if exists "users can send request messages" on public.request_messages;
create policy "users can send request messages" on public.request_messages for insert to authenticated with check(sender_id=auth.uid() and sender_role='user' and exists(select 1 from public.contact_requests r where r.id=request_id and r.user_id=auth.uid()));

drop policy if exists "public can read site content" on public.site_content;
create policy "public can read site content" on public.site_content for select to anon,authenticated using(true);
drop policy if exists "admins can manage site content" on public.site_content;
create policy "admins can manage site content" on public.site_content for all to authenticated using(exists(select 1 from public.admin_users a where a.user_id=auth.uid())) with check(exists(select 1 from public.admin_users a where a.user_id=auth.uid()));

create or replace function public.nexora_sync_profile()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(user_id,email,full_name,provider)
  values(new.id,new.email,new.raw_user_meta_data->>'full_name',coalesce(new.raw_app_meta_data->>'provider','email'))
  on conflict(user_id) do update set email=excluded.email, full_name=coalesce(excluded.full_name,profiles.full_name), provider=excluded.provider, updated_at=now();
  return new;
end;
$$;
drop trigger if exists nexora_sync_profile_trigger on auth.users;
create trigger nexora_sync_profile_trigger after insert or update of email,raw_user_meta_data,raw_app_meta_data on auth.users for each row execute function public.nexora_sync_profile();

insert into public.profiles(user_id,email,full_name,provider)
select id,email,raw_user_meta_data->>'full_name',coalesce(raw_app_meta_data->>'provider','email') from auth.users
on conflict(user_id) do update set email=excluded.email, full_name=coalesce(excluded.full_name,profiles.full_name), provider=excluded.provider, updated_at=now();

-- Compte Google administrateur Nexora. Le compte demandé est nexora.platform@gmail.com.
create or replace function public.nexora_auto_admin()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if lower(coalesce(new.email,'')) = lower('nexora.platform@gmail.com') then
    insert into public.admin_users(user_id) values(new.id) on conflict(user_id) do nothing;
  end if;
  return new;
end;
$$;
drop trigger if exists nexora_auto_admin_trigger on auth.users;
create trigger nexora_auto_admin_trigger after insert on auth.users for each row execute function public.nexora_auto_admin();
insert into public.admin_users(user_id) select id from auth.users where lower(email) = lower('nexora.platform@gmail.com') on conflict(user_id) do nothing;

-- Catalogue : image facultative pour les sites.
alter table public.catalog_items add column if not exists image_url text;

-- Contenu initial de l'éditeur : les valeurs sont fusionnées avec les valeurs par défaut du code.
insert into public.site_content(page_key,content) values
('home','{}'::jsonb),('formations','{}'::jsonb),('services','{}'::jsonb),('sites','{}'::jsonb),('contact','{}'::jsonb)
on conflict(page_key) do nothing;

-- Stockage des images utilisées par l'éditeur et les sites.
insert into storage.buckets (id,name,public) values ('nexora-media','nexora-media',true)
on conflict (id) do update set public=true;
drop policy if exists "admins can upload nexora media" on storage.objects;
create policy "admins can upload nexora media" on storage.objects for insert to authenticated with check(bucket_id='nexora-media' and exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
drop policy if exists "admins can update nexora media" on storage.objects;
create policy "admins can update nexora media" on storage.objects for update to authenticated using(bucket_id='nexora-media' and exists(select 1 from public.admin_users a where a.user_id=auth.uid())) with check(bucket_id='nexora-media' and exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
drop policy if exists "admins can delete nexora media" on storage.objects;
create policy "admins can delete nexora media" on storage.objects for delete to authenticated using(bucket_id='nexora-media' and exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
