-- Nexora V1.6.49 — cycle de vie des abonnements (gestion manuelle, sans paiement)
alter table public.user_subscriptions add column if not exists starts_at timestamptz;
alter table public.user_subscriptions add column if not exists expires_at timestamptz;
alter table public.user_subscriptions add column if not exists status text not null default 'active';
alter table public.user_subscriptions add column if not exists renewed_at timestamptz;
alter table public.user_subscriptions add column if not exists renewal_count integer not null default 0;

update public.user_subscriptions
set starts_at = coalesce(starts_at, assigned_at),
    status = case when expires_at is not null and expires_at <= now() then 'expired' else 'active' end
where starts_at is null or status is null;

create table if not exists public.user_subscription_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  subscription_id bigint references public.subscriptions(id) on delete set null,
  subscription_slug text,
  subscription_name text,
  starts_at timestamptz,
  expires_at timestamptz,
  action text not null default 'changed',
  created_at timestamptz not null default now()
);

alter table public.user_subscription_history enable row level security;
drop policy if exists "users can read own subscription history" on public.user_subscription_history;
create policy "users can read own subscription history" on public.user_subscription_history
  for select to authenticated using (user_id = auth.uid());
drop policy if exists "staff can manage subscription history" on public.user_subscription_history;
create policy "staff can manage subscription history" on public.user_subscription_history
  for all to authenticated
  using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()))
  with check (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));
