-- Nexora V1.6.63 — panier + moyens de paiement configurables
-- À exécuter dans Supabase > SQL Editor.

create table if not exists public.store_settings (
  id integer primary key default 1 check (id = 1),
  enabled boolean not null default true,
  updated_at timestamptz not null default now()
);
insert into public.store_settings (id, enabled) values (1, true) on conflict (id) do nothing;

create table if not exists public.payment_methods (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  icon text,
  mode text not null default 'manual' check (mode in ('manual','link','external')),
  instructions text,
  payment_url text,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  payment_method_id bigint references public.payment_methods(id) on delete set null,
  status text not null default 'pending' check (status in ('pending','confirmed','processing','completed','cancelled')),
  total numeric(10,2) not null default 0,
  currency text not null default 'EUR',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  catalog_type text not null check (catalog_type in ('formation','service')),
  catalog_slug text not null,
  title text not null,
  unit_price numeric(10,2),
  quantity integer not null default 1 check (quantity between 1 and 99),
  created_at timestamptz not null default now()
);

alter table public.store_settings enable row level security;
alter table public.payment_methods enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "public can read store settings" on public.store_settings;
create policy "public can read store settings" on public.store_settings for select to anon, authenticated using (id = 1);

drop policy if exists "public can read active payment methods" on public.payment_methods;
create policy "public can read active payment methods" on public.payment_methods for select to anon, authenticated using (active = true);

drop policy if exists "users can read own orders" on public.orders;
create policy "users can read own orders" on public.orders for select to authenticated using (user_id = auth.uid());

drop policy if exists "users can create own orders" on public.orders;
create policy "users can create own orders" on public.orders for insert to authenticated with check (user_id = auth.uid());

drop policy if exists "users can read own order items" on public.order_items;
create policy "users can read own order items" on public.order_items for select to authenticated using (
  exists (select 1 from public.orders o where o.id = order_id and o.user_id = auth.uid())
);

drop policy if exists "admins can manage store settings" on public.store_settings;
create policy "admins can manage store settings" on public.store_settings for all to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()))
with check (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));

drop policy if exists "admins can manage payment methods" on public.payment_methods;
create policy "admins can manage payment methods" on public.payment_methods for all to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()))
with check (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));

drop policy if exists "admins can manage orders" on public.orders;
create policy "admins can manage orders" on public.orders for all to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()))
with check (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));

drop policy if exists "admins can manage order items" on public.order_items;
create policy "admins can manage order items" on public.order_items for all to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()))
with check (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));

insert into public.payment_methods (name, description, icon, mode, instructions, payment_url, active, sort_order)
select 'Paiement à définir', 'Moyen de paiement à configurer depuis le panneau propriétaire.', '💳', 'manual',
       'Le propriétaire vous communiquera les modalités de paiement.', null, false, 99
where not exists (select 1 from public.payment_methods);
