"use client";
import { useState } from "react";
import { CheckCircle2, Mail, MessageCircle, Phone, Send, Sparkles } from "lucide-react";
import Header from "../ui/Header";
import Footer from "../ui/Footer";
export default function Contact(){const [sent,setSent]=useState(false);return <main><Header/><section className="pageHero"><span className="sectionTag">NOUS CONTACTER</span><h1>Un projet ?<br/><span>Parlons-en.</span></h1><p>Décrivez votre besoin en quelques lignes. Cette première demande permet de préparer un échange précis.</p></section>
<section className="contactLayout"><div className="contactInfo"><div className="contactLead"><Sparkles size={18}/><strong>Construisons la suite.</strong><p>Que ce soit une création, une correction, une optimisation ou une formation, expliquez simplement ce que vous souhaitez.</p></div><div className="contactMethod"><div className="icon"><MessageCircle size={20}/></div><div><strong>Chat Nexora</strong><span>La messagerie intégrée arrivera dans une prochaine version.</span></div></div><div className="contactMethod"><div className="icon"><Mail size={20}/></div><div><strong>Email professionnel</strong><span>Une adresse professionnelle sera ajoutée ici.</span></div></div><div className="contactMethod"><div className="icon"><Phone size={20}/></div><div><strong>Téléphone</strong><span>Le numéro professionnel sera ajouté ici.</span></div></div></div>
<form className="contactForm" onSubmit={e=>{e.preventDefault();setSent(true)}}>{sent?<div className="success"><CheckCircle2 size={44}/><h2>Demande préparée !</h2><p>Le formulaire est prêt côté interface. L'envoi réel sera connecté au backend Nexora dans une prochaine version.</p><button type="button" className="secondary" onClick={()=>setSent(false)}>Nouvelle demande</button></div>:<><div className="formRow"><label>Nom<input required placeholder="Votre nom"/></label><label>Email<input required type="email" placeholder="vous@exemple.fr"/></label></div><div className="formRow"><label>Type de demande<select defaultValue="Projet"><option>Projet</option><option>Formation</option><option>Développement</option><option>Site web</option><option>Optimisation</option><option>Accompagnement</option><option>Autre</option></select></label><label>Budget indicatif<select defaultValue="Je ne sais pas"><option>Je ne sais pas</option><option>Moins de 50 €</option><option>50 – 150 €</option><option>150 – 300 €</option><option>300 € et +</option></select></label></div><label>Sujet<input required placeholder="Ex : Création d'un site vitrine"/></label><label>Votre message<textarea required rows="7" placeholder="Expliquez-nous votre besoin..."></textarea></label><button className="primary" type="submit">Envoyer la demande <Send size={17}/></button></>}</form></section>
<Footer /></main>}
