"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {createClient} from "../../../lib/supabase/client";
import {ArrowLeft,Save,Plus,Trash2,GripVertical,Image as ImageIcon,Type,Heading,Link2,Minus,LoaderCircle,Upload} from "lucide-react";
const pages=["home","formations","services","sites","contact"];
const labels={home:"Accueil",formations:"Formations",services:"Nos services",sites:"Nos sites",contact:"Nous contacter"};
const block=(type="text")=>({id:crypto.randomUUID(),type,title:"",text:"",eyebrow:"",url:"",alt:"",href:"/contact",active:true});
export default function Editor(){const [page,setPage]=useState("home"),[data,setData]=useState({}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState("");
 useEffect(()=>{fetch("/api/admin/editor").then(r=>r.json()).then(j=>{if(j.pages){const x={};j.pages.forEach(p=>x[p.page_key]=p.content||{});setData(x)}else setError(j.error||"Erreur")}).catch(()=>setError("Impossible de charger l'éditeur.")).finally(()=>setLoading(false))},[]);
 const c=data[page]||{}; const set=(key,val)=>setData(d=>({...d,[page]:{...(d[page]||{}),[key]:val}}));
 async function save(){setSaving(true);setError("");setOk("");const r=await fetch("/api/admin/editor",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({page_key:page,content:c})});const j=await r.json();if(!r.ok)setError(j.error||"Erreur");else setOk("Modifications enregistrées.");setSaving(false)}
 function blocks(){return Array.isArray(c.customBlocks)?c.customBlocks:[]};function addBlock(type){set("customBlocks":[...blocks(),block(type)])};function updateBlock(id,key,val){set("customBlocks",blocks().map(b=>b.id===id?{...b,[key]:val}:b))};function delBlock(id){set("customBlocks",blocks().filter(b=>b.id!==id))}
 if(loading)return <main className="adminPage"><div className="adminEmpty"><LoaderCircle className="spin"/> Chargement de l'éditeur…</div></main>;
 return <main className="adminPage"><header className="adminTop"><div><Link href="/admin" className="editorBack"><ArrowLeft size={15}/> Admin</Link><span className="sectionTag">ÉDITEUR NEXORA</span><h1>Construisez le <span>site.</span></h1><p>Modifiez les textes, sections, boutons et blocs sans toucher au code.</p></div><div className="adminActions"><Link className="secondary" href="/">Voir le site</Link><button className="primary" onClick={save} disabled={saving}>{saving?<><LoaderCircle className="spin" size={16}/> Enregistrement</>:<><Save size={16}/> Enregistrer</>}</button></div></header>
 <section className="editorWrap"><div className="editorPageTabs">{pages.map(p=><button className={page===p?"active":""} key={p} onClick={()=>{setPage(p);setOk("")}}>{labels[p]}</button>)}</div>
 <div className="editorCard"><div className="editorCardHead"><div><span className="sectionTag">PAGE</span><h2>{labels[page]}</h2></div><span className="editorHint">Les changements sont sauvegardés dans Supabase.</span></div>
 {page!=="contact"&&<><Field label="Petit titre / eyebrow" value={c.eyebrow} onChange={v=>set("eyebrow",v)}/><div className="editorTwo"><Field label="Titre" value={c.title} onChange={v=>set("title",v)}/><Field label="Texte accentué" value={c.accent} onChange={v=>set("accent",v)}/></div><Field label="Description" value={c.text} area onChange={v=>set("text",v)}/><div className="toggleGrid">{[["showStats","Statistiques"],["showIntro","Introduction"],["showPillars","Blocs principaux"],["showFeature","Bloc formations"],["showCta","CTA final"]].map(([k,l])=><Toggle key={k} label={l} checked={c[k]!==false} onChange={v=>set(k,v)}/>)}</div></>}
 {page==="home"&&<><div className="editorTwo"><Field label="Bouton principal" value={c.primaryLabel} onChange={v=>set("primaryLabel",v)}/><Field label="Lien principal" value={c.primaryHref} onChange={v=>set("primaryHref",v)}/></div><div className="editorTwo"><Field label="Second bouton" value={c.secondaryLabel} onChange={v=>set("secondaryLabel",v)}/><Field label="Lien secondaire" value={c.secondaryHref} onChange={v=>set("secondaryHref",v)}/></div><ArrayEditor title="Arguments de confiance" values={c.trust||[]} onChange={v=>set("trust",v)}/><ArrayEditor title="Blocs principaux de l’accueil" values={c.pillars||[]} objectFields={["icon","title","text","href"]} onChange={v=>set("pillars",v)}/><ArrayEditor title="Statistiques" values={c.stats||[]} objectFields={["value","label"]} onChange={v=>set("stats",v)}/><div className="editorTwo"><Field label="Intro — eyebrow" value={c.introEyebrow} onChange={v=>set("introEyebrow",v)}/><Field label="Intro — titre" value={c.introTitle} onChange={v=>set("introTitle",v)}/></div><div className="editorTwo"><Field label="Intro — accent" value={c.introAccent} onChange={v=>set("introAccent",v)}/><Field label="Intro — texte" value={c.introText} area onChange={v=>set("introText",v)}/></div><div className="editorTwo"><Field label="Formation — eyebrow" value={c.featureEyebrow} onChange={v=>set("featureEyebrow",v)}/><Field label="Formation — titre" value={c.featureTitle} onChange={v=>set("featureTitle",v)}/></div><div className="editorTwo"><Field label="Formation — accent" value={c.featureAccent} onChange={v=>set("featureAccent",v)}/><Field label="Formation — texte" value={c.featureText} area onChange={v=>set("featureText",v)}/></div><div className="editorTwo"><Field label="CTA — eyebrow" value={c.ctaEyebrow} onChange={v=>set("ctaEyebrow",v)}/><Field label="CTA — titre" value={c.ctaTitle} onChange={v=>set("ctaTitle",v)}/></div><div className="editorTwo"><Field label="CTA — accent" value={c.ctaAccent} onChange={v=>set("ctaAccent",v)}/><Field label="CTA — texte" value={c.ctaText} area onChange={v=>set("ctaText",v)}/></div></>}
 {page==="formations"&&<><div className="editorTwo"><Field label="Titre du CTA" value={c.ctaTitle} onChange={v=>set("ctaTitle",v)}/><Field label="Texte du CTA" value={c.ctaText} area onChange={v=>set("ctaText",v)}/></div><Toggle label="Afficher le CTA final" checked={c.showCta!==false} onChange={v=>set("showCta",v)}/><p className="editorNote">Les formations, leurs noms, descriptions, prix, niveaux et modules se gèrent depuis <b>Admin → Formations</b>.</p></>}
 {page==="services"&&<><Toggle label="Afficher le bloc processus" checked={c.showProcess!==false} onChange={v=>set("showProcess",v)}/><div className="editorTwo"><Field label="Process — eyebrow" value={c.processEyebrow} onChange={v=>set("processEyebrow",v)}/><Field label="Process — titre" value={c.processTitle} onChange={v=>set("processTitle",v)}/></div><Field label="Process — accent" value={c.processAccent} onChange={v=>set("processAccent",v)}/><ArrayEditor title="Étapes" values={c.steps||[]} objectFields={["number","title","text"]} onChange={v=>set("steps",v)}/><div className="editorTwo"><Field label="CTA — eyebrow" value={c.ctaEyebrow} onChange={v=>set("ctaEyebrow",v)}/><Field label="CTA — titre" value={c.ctaTitle} onChange={v=>set("ctaTitle",v)}/></div><Field label="CTA — texte" value={c.ctaText} onChange={v=>set("ctaText",v)}/><Toggle label="Afficher le CTA final" checked={c.showCta!==false} onChange={v=>set("showCta",v)}/><p className="editorNote">Les services, prix, icônes et descriptions se gèrent depuis <b>Admin → Services</b>.</p></>}
 {page==="sites"&&<><Toggle label="Afficher l’écosystème" checked={c.showEcosystem!==false} onChange={v=>set("showEcosystem",v)}/><div className="editorTwo"><Field label="Écosystème — eyebrow" value={c.ecoEyebrow} onChange={v=>set("ecoEyebrow",v)}/><Field label="Écosystème — titre" value={c.ecoTitle} onChange={v=>set("ecoTitle",v)}/></div><div className="editorTwo"><Field label="Écosystème — accent" value={c.ecoAccent} onChange={v=>set("ecoAccent",v)}/><Field label="Écosystème — texte" value={c.ecoText} area onChange={v=>set("ecoText",v)}/></div><p className="editorNote">Les sites, noms, descriptions, liens et images se gèrent depuis <b>Admin → Nos sites</b>.</p></>}
 {page==="contact"&&<><Field label="Petit titre / eyebrow" value={c.eyebrow} onChange={v=>set("eyebrow",v)}/><div className="editorTwo"><Field label="Titre" value={c.title} onChange={v=>set("title",v)}/><Field label="Texte accentué" value={c.accent} onChange={v=>set("accent",v)}/></div><Field label="Description" value={c.text} area onChange={v=>set("text",v)}/><div className="toggleGrid"><Toggle label="Afficher les coordonnées" checked={c.showContactInfo!==false} onChange={v=>set("showContactInfo",v)}/><Toggle label="Afficher le formulaire" checked={c.showForm!==false} onChange={v=>set("showForm",v)}/></div><div className="editorTwo"><Field label="Bloc d'introduction — titre" value={c.leadTitle} onChange={v=>set("leadTitle",v)}/><Field label="Bloc d'introduction — texte" value={c.leadText} area onChange={v=>set("leadText",v)}/></div><div className="editorTwo"><Field label="Email professionnel" value={c.email} onChange={v=>set("email",v)}/><Field label="Téléphone professionnel" value={c.phone} onChange={v=>set("phone",v)}/></div><Field label="Texte du bloc Chat" value={c.chatText} onChange={v=>set("chatText",v)}/></>}
 <CustomBlocks page={page} blocks={blocks()} addBlock={addBlock} updateBlock={updateBlock} delBlock={delBlock}/>
 </div></section></main>}
function Toggle({label,checked,onChange}){return <label className="toggleField"><input type="checkbox" checked={checked!==false} onChange={e=>onChange(e.target.checked)}/><span>{label}</span></label>}
function Field({label,value,onChange,area=false}){return <label className="editorField">{label}{area?<textarea rows={4} value={value||""} onChange={e=>onChange(e.target.value)}/>:<input value={value||""} onChange={e=>onChange(e.target.value)}/>}</label>}
function ArrayEditor({title,values,onChange,objectFields=[]}){const arr=Array.isArray(values)?values:[];function update(i,key,val){const n=[...arr];if(objectFields.length){n[i]={...n[i],[key]:val}}else n[i]=val;onChange(n)}return <div className="arrayEditor"><div className="arrayHead"><strong>{title}</strong><button type="button" onClick={()=>onChange([...arr,objectFields.length?Object.fromEntries(objectFields.map(k=>[k,""])):""])}><Plus size={14}/> Ajouter</button></div>{arr.map((v,i)=><div className="arrayRow" key={i}>{objectFields.length?objectFields.map(k=><input key={k} placeholder={k} value={v?.[k]||""} onChange={e=>update(i,k,e.target.value)}/>):<input value={v||""} onChange={e=>update(i,null,e.target.value)}/>}<button type="button" onClick={()=>onChange(arr.filter((_,x)=>x!==i))}><Trash2 size={15}/></button></div>)}</div>}
function CustomBlocks({page,blocks,addBlock,updateBlock,delBlock}){return <div className="customEditor"><div className="arrayHead"><div><span className="sectionTag">BLOCS LIBRES</span><strong>Ajouter du contenu à la page</strong></div><div className="blockAdd"><button onClick={()=>addBlock("heading")}><Heading size={14}/> Titre</button><button onClick={()=>addBlock("text")}><Type size={14}/> Texte</button><button onClick={()=>addBlock("image")}><ImageIcon size={14}/> Image</button><button onClick={()=>addBlock("button")}><Link2 size={14}/> Bouton</button><button onClick={()=>addBlock("divider")}><Minus size={14}/> Séparateur</button></div></div>{blocks.map((b,i)=><article className="blockEditor" key={b.id}><div className="blockBar"><GripVertical size={15}/><strong>Bloc {i+1} · {b.type}</strong><button onClick={()=>delBlock(b.id)}><Trash2 size={15}/></button></div>{b.type!=="divider"&&<div className="editorTwo"><Field label="Titre" value={b.title} onChange={v=>updateBlock(b.id,"title",v)}/><Field label="Petit titre" value={b.eyebrow} onChange={v=>updateBlock(b.id,"eyebrow",v)}/></div>}{b.type!=="divider"&&b.type!=="button"&&<Field label="Texte" value={b.text} area onChange={v=>updateBlock(b.id,"text",v)}/>} {b.type==="image"&&<div className="editorTwo"><Field label="URL de l'image" value={b.url} onChange={v=>updateBlock(b.id,"url",v)}/><Field label="Texte alternatif" value={b.alt} onChange={v=>updateBlock(b.id,"alt",v)}/><ImageUpload page={page} block={b} onUploaded={v=>updateBlock(b.id,"url",v)}/></div>} {b.type==="button"&&<Field label="Lien" value={b.href} onChange={v=>updateBlock(b.id,"href",v)}/>}</article>)}</div>}

function ImageUpload({page,block,onUploaded}){const [loading,setLoading]=useState(false);const [error,setError]=useState("");async function upload(e){const file=e.target.files?.[0];if(!file)return;if(!file.type.startsWith("image/")){setError("Sélectionnez une image.");return}setLoading(true);setError("");const supabase=createClient();const ext=file.name.split(".").pop()?.toLowerCase()||"png";const path=`site/${page}/${crypto.randomUUID()}.${ext}`;const {error:up}=await supabase.storage.from("nexora-media").upload(path,file,{contentType:file.type,upsert:false});if(up)setError(up.message);else{const {data}=supabase.storage.from("nexora-media").getPublicUrl(path);onUploaded(data.publicUrl)}setLoading(false)}return <label className="imageUpload">{loading?<><LoaderCircle className="spin" size={14}/> Téléversement…</>:<><Upload size={14}/> Importer une image<input type="file" accept="image/*" onChange={upload}/></>}{error&&<small>{error}</small>}</label>}
