import { NextResponse } from "next/server";
import { getAdminContext, can } from "../../../../lib/nexora/admin";

async function guard(permission="staff") {
  const ctx = await getAdminContext();
  if (!ctx.userId) return { ...ctx, response: NextResponse.json({error:"Non authentifié"},{status:401}) };
  if (!ctx.role || !can(ctx.role, permission)) return { ...ctx, response: NextResponse.json({error:"Permission insuffisante"},{status:403}) };
  return ctx;
}
export async function GET(){const ctx=await guard("users_read");if(ctx.response)return ctx.response;const {data,error}=await ctx.supabase.from("admin_users").select("user_id,role,permissions,created_at");if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({staff:data||[]});}
export async function POST(request){const ctx=await guard("staff");if(ctx.response)return ctx.response;const body=await request.json();if(!body.user_id)return NextResponse.json({error:"Utilisateur obligatoire"},{status:400});const role=["owner","admin","editor","support"].includes(body.role)?body.role:"support";if(role==="owner"&&ctx.role!=="owner")return NextResponse.json({error:"Seul le propriétaire peut nommer un propriétaire."},{status:403});const {data,error}=await ctx.supabase.from("admin_users").upsert({user_id:body.user_id,role,permissions:body.permissions||{}},{onConflict:"user_id"}).select().single();if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({staff:data});}
export async function PATCH(request){const ctx=await guard("staff");if(ctx.response)return ctx.response;const body=await request.json();if(!body.user_id)return NextResponse.json({error:"Utilisateur obligatoire"},{status:400});const {data:target}=await ctx.supabase.from("admin_users").select("role").eq("user_id",body.user_id).maybeSingle();if(target?.role==="owner"&&ctx.role!=="owner")return NextResponse.json({error:"Le propriétaire ne peut être modifié que par le propriétaire."},{status:403});const role=["owner","admin","editor","support"].includes(body.role)?body.role:null;if(role==="owner"&&ctx.role!=="owner")return NextResponse.json({error:"Seul le propriétaire peut nommer un propriétaire."},{status:403});const patch={};if(role)patch.role=role;if(body.permissions!==undefined)patch.permissions=body.permissions;const {data,error}=await ctx.supabase.from("admin_users").update(patch).eq("user_id",body.user_id).select().single();if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({staff:data});}
export async function DELETE(request){const ctx=await guard("staff");if(ctx.response)return ctx.response;const body=await request.json();if(!body.user_id)return NextResponse.json({error:"Utilisateur obligatoire"},{status:400});const {data:target}=await ctx.supabase.from("admin_users").select("role").eq("user_id",body.user_id).maybeSingle();if(target?.role==="owner")return NextResponse.json({error:"Le propriétaire ne peut pas être retiré."},{status:403});if(body.user_id===ctx.userId)return NextResponse.json({error:"Vous ne pouvez pas retirer vos propres droits."},{status:400});const {error}=await ctx.supabase.from("admin_users").delete().eq("user_id",body.user_id);if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({ok:true});}
