"use client";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, LoaderCircle, Mail, LockKeyhole, Bell, Trash2, UserRound, LogOut, Save } from "lucide-react";
import { useEffect, useState } from "react";
import { createClient } from "../../lib/supabase/client";
import Header from "../ui/Header";
import Footer from "../ui/Footer";

export default function Parametres(){
  const [user,setUser]=useState(null),[name,setName]=useState(""),[email,setEmail]=useState(""),[newEmail,setNewEmail]=useState("");
  const [password,setPassword]=useState(""),[password2,setPassword2]=useState(""),[messages,setMessages]=useState(true),[academy,setAcademy]=useState(true);
  const [loading,setLoading]=useState(true),[saving,setSaving]=useState(""),[notice,setNotice]=useState(""),[error,setError]=useState(""),[deleting,setDeleting]=useState(false);
  useEffect(()=>{(async()=>{const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href="/connexion";return}setUser(user);setName(user.user_metadata?.full_name||"");setEmail(user.email||"");setNewEmail(user.email||"");try{setMessages(localStorage.getItem("nexora_notify_messages")!=="false");setAcademy(localStorage.getItem("nexora_notify_academy")!=="false")}catch{}setLoading(false)})()},[]);
  function flash(v){setError("");setNotice(v);window.setTimeout(()=>setNotice(""),4500)}
  async function saveProfile(e){e.preventDefault();setSaving("profile");setError("");const {error}=await createClient().auth.updateUser({data:{full_name:name.trim()}});if(error)setError(error.message);else flash("Vos informations ont bien été enregistrées.");setSaving("")}
  async function changeEmail(e){e.preventDefault();setSaving("email");setError("");if(!newEmail.trim()||newEmail.trim().toLowerCase()===email.toLowerCase()){setError("Saisissez une nouvelle adresse email.");setSaving("");return}const {error}=await createClient().auth.updateUser({email:newEmail.trim()});if(error)setError(error.message);else{flash("Demande de changement envoyée. Une confirmation peut être nécessaire par email.") }setSaving("")}
  async function changePassword(e){e.preventDefault();setSaving("password");setError("");if(password.length<6){setError("Le nouveau mot de passe doit contenir au moins 6 caractères.");setSaving("");return}if(password!==password2){setError("Les deux mots de passe ne correspondent pas.");setSaving("");return}const {error}=await createClient().auth.updateUser({password});if(error)setError(error.message);else{setPassword("");setPassword2("");flash("Votre mot de passe a été modifié.")}setSaving("")}
  function saveNotifications(m,a){setMessages(m);setAcademy(a);try{localStorage.setItem("nexora_notify_messages",String(m));localStorage.setItem("nexora_notify_academy",String(a))}catch{}flash("Préférences de notifications enregistrées sur cet appareil.")}
  async function requestDeletion(){if(!user||deleting)return;if(!window.confirm("Confirmer la demande de suppression de votre compte ? L'équipe Nexora vous contactera avant toute suppression définitive."))return;setDeleting(true);setError("");const f=new FormData();f.set("name",name||user.email?.split("@")[0]||"Utilisateur Nexora");f.set("email",user.email||"");f.set("request_type","Suppression de compte");f.set("budget","Je ne sais pas");f.set("project_type","Autre");f.set("deadline","Sans délai précis");f.set("urgency","Normale");f.set("subject","Demande de suppression de mon compte");f.set("message","Je souhaite demander la suppression de mon compte Nexora et de mes données personnelles. Merci de me contacter pour confirmer la procédure.");try{const r=await fetch("/api/contact",{method:"POST",body:f}),j=await r.json();if(!r.ok)throw new Error(j.error||"Impossible d'envoyer la demande.");flash("Votre demande de suppression a été envoyée à l'équipe Nexora.")}catch(e){setError(e.message||"Impossible d'envoyer la demande.")}setDeleting(false)}
  async function logout(){await createClient().auth.signOut();window.location.href="/"}
  if(loading)return <main><Header/><section className="authPage"><div className="authCard"><LoaderCircle className="spin" size={24}/></div></section><Footer/></main>;
  return <main><Header/><section className="subPage settingsPage"><div className="subHero settingsHero"><span className="sectionTag">PARAMÈTRES</span><h1>Mon compte,<br/><span>mes réglages.</span></h1><p className="lead">Gérez vos informations, votre sécurité et vos préférences Nexora depuis un seul endroit.</p>
    {notice&&<div className="settingsNotice success"><CheckCircle2 size={16}/>{notice}</div>}{error&&<div className="settingsNotice error">{error}</div>}
    <div className="settingsGrid">
      <section className="settingsCard"><Head icon={<UserRound size={18}/>} tag="PROFIL" title="Informations personnelles"/><form onSubmit={saveProfile} className="settingsForm"><label>Nom affiché<input value={name} onChange={e=>setName(e.target.value)} placeholder="Votre nom" required/></label><label>Email actuel<input value={email} type="email" disabled/></label><button className="primary" disabled={saving==="profile"}>{saving==="profile"?<><LoaderCircle className="spin" size={15}/> Enregistrement...</>:<><Save size={15}/> Enregistrer</>}</button></form></section>
      <section className="settingsCard"><Head icon={<Mail size={18}/>} tag="EMAIL" title="Changer d'adresse"/><form onSubmit={changeEmail} className="settingsForm"><label>Nouvelle adresse email<input value={newEmail} onChange={e=>setNewEmail(e.target.value)} type="email" required/></label><p className="settingsHint">Supabase peut demander une confirmation avant de finaliser le changement.</p><button className="secondary" disabled={saving==="email"}>{saving==="email"?<><LoaderCircle className="spin" size={15}/> Envoi...</>:<>Demander le changement →</>}</button></form></section>
      <section className="settingsCard"><Head icon={<LockKeyhole size={18}/>} tag="SÉCURITÉ" title="Nouveau mot de passe"/><form onSubmit={changePassword} className="settingsForm"><label>Nouveau mot de passe<input value={password} onChange={e=>setPassword(e.target.value)} type="password" minLength={6} required/></label><label>Confirmation<input value={password2} onChange={e=>setPassword2(e.target.value)} type="password" minLength={6} required/></label><button className="secondary" disabled={saving==="password"}>{saving==="password"?<><LoaderCircle className="spin" size={15}/> Modification...</>:<>Modifier le mot de passe →</>}</button></form></section>
      <section className="settingsCard"><Head icon={<Bell size={18}/>} tag="NOTIFICATIONS" title="Mes préférences"/><div className="settingsOptions"><Toggle label="Messages Nexora" text="Préférence pour les nouveaux échanges." checked={messages} onChange={v=>saveNotifications(v,academy)}/><Toggle label="Nexora Academy" text="Préférence pour votre progression." checked={academy} onChange={v=>saveNotifications(messages,v)}/></div><p className="settingsHint">Ces préférences sont enregistrées sur cet appareil.</p></section>
      <section className="settingsCard settingsAppearance"><Head icon="✦" tag="APPARENCE" title="Expérience Nexora"/><div className="appearanceChoice"><div><strong>Interface sombre</strong><span>L'identité visuelle Nexora reste en mode sombre.</span></div><b>ACTIF</b></div></section>
      <section className="settingsCard settingsDanger"><Head icon={<Trash2 size={18}/>} tag="DONNÉES & COMPTE" title="Suppression du compte"/><p>Demandez la suppression de votre compte et de vos données personnelles. L'équipe Nexora vous contactera pour vérifier la demande.</p><button className="dangerButton" onClick={requestDeletion} disabled={deleting}>{deleting?<><LoaderCircle className="spin" size={15}/> Envoi...</>:<><Trash2 size={15}/> Demander la suppression</>}</button></section>
    </div><div className="settingsFooter"><Link href="/compte" className="secondary"><ArrowLeft size={14}/> Retour à mon espace</Link><button className="secondary" onClick={logout}><LogOut size={14}/> Se déconnecter</button></div>
  </div></section><Footer/></main>
}
function Head({icon,tag,title}){return <div className="settingsHead"><div className="settingsIcon">{icon}</div><div><span>{tag}</span><h2>{title}</h2></div></div>}
function Toggle({label,text,checked,onChange}){return <button type="button" className={`settingsToggle ${checked?"active":""}`} onClick={()=>onChange(!checked)}><span><strong>{label}</strong><small>{text}</small></span><i><b/></i></button>}
