import {NextResponse} from "next/server";
import {getAdminContext,can} from "../../../../lib/nexora/admin";
async function guard(){const ctx=await getAdminContext();if(!ctx.userId)return {supabase:null,response:NextResponse.json({error:"Non authentifié"},{status:401})};if(!ctx.role||!can(ctx.role,"catalog",ctx.permissions))return {supabase:null,response:NextResponse.json({error:"Permission insuffisante"},{status:403})};return {supabase:ctx.supabase,response:null};}
const clean=x=>({name:String(x.name||"").trim(),description:String(x.description||"").trim(),icon:String(x.icon||"💳").trim(),mode:["manual","link","external"].includes(x.mode)?x.mode:"manual",instructions:String(x.instructions||"").trim(),payment_url:String(x.payment_url||"").trim()||null,active:x.active!==false,sort_order:Number(x.sort_order)||0,updated_at:new Date().toISOString()});
export async function GET(){const {supabase,response}=await guard();if(response)return response;const [{data:settings},{data:methods}]=await Promise.all([supabase.from("store_settings").select("*").eq("id",1).maybeSingle(),supabase.from("payment_methods").select("*").order("sort_order").order("created_at")]);return NextResponse.json({settings:settings||{id:1,enabled:true},methods:methods||[]});}
export async function PATCH(request){const {supabase,response}=await guard();if(response)return response;const b=await request.json();if(b.settings){const {data,error}=await supabase.from("store_settings").upsert({id:1,enabled:b.settings.enabled!==false,updated_at:new Date().toISOString()}).select().single();if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({settings:data});}if(!b.id)return NextResponse.json({error:"ID obligatoire"},{status:400});const p=clean(b);if(!p.name)return NextResponse.json({error:"Nom obligatoire"},{status:400});if((p.mode==="link"||p.mode==="external")&&!p.payment_url)return NextResponse.json({error:"Un lien est obligatoire pour ce mode."},{status:400});
  if(p.payment_url){try{const u=new URL(p.payment_url);if(!["http:","https:"].includes(u.protocol))throw new Error()}catch{return NextResponse.json({error:"Le lien de paiement doit commencer par http:// ou https://."},{status:400})}}const {data,error}=await supabase.from("payment_methods").update(p).eq("id",b.id).select().single();if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({item:data});}
export async function POST(request){const {supabase,response}=await guard();if(response)return response;const p=clean(await request.json());if(!p.name)return NextResponse.json({error:"Nom obligatoire"},{status:400});if((p.mode==="link"||p.mode==="external")&&!p.payment_url)return NextResponse.json({error:"Un lien est obligatoire pour ce mode."},{status:400});
  if(p.payment_url){try{const u=new URL(p.payment_url);if(!["http:","https:"].includes(u.protocol))throw new Error()}catch{return NextResponse.json({error:"Le lien de paiement doit commencer par http:// ou https://."},{status:400})}}const {data,error}=await supabase.from("payment_methods").insert(p).select().single();if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({item:data});}
export async function DELETE(request){const {supabase,response}=await guard();if(response)return response;const b=await request.json();if(!b.id)return NextResponse.json({error:"ID obligatoire"},{status:400});const {error}=await supabase.from("payment_methods").delete().eq("id",b.id);if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({ok:true});}
