"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {Users,LoaderCircle,ShieldCheck,Save,Trash2,LogOut,Search,UserRound,Plus,Pencil,X,Check} from "lucide-react";
import {createClient} from "../../../lib/supabase/client";
import AdminControlNav from "../AdminControlNav";

const ACCESS=[
 ["users_read","Voir les utilisateurs"],["users_manage","Gérer les utilisateurs"],["staff_manage","Gérer le staff et les rôles"],
 ["catalog","Gérer le catalogue"],["editor","Modifier l'éditeur du site"],["site_pages","Gérer les pages"],["requests","Voir les demandes clients"],["requests_manage","Gérer et répondre aux demandes"]
];
const tones=["violet","blue","green","orange","pink","cyan"];
const emptyRole={name:"",description:"",permissions:[]};

export default function AdminUsers({embedded=false}){
 const [users,setUsers]=useState([]),[staff,setStaff]=useState([]),[roles,setRoles]=useState([]),[assignments,setAssignments]=useState([]),[subscriptions,setSubscriptions]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[saving,setSaving]=useState(""),[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[open,setOpen]=useState(null),[roleEditor,setRoleEditor]=useState(null),[roleForm,setRoleForm]=useState(emptyRole),[showRoleCreator,setShowRoleCreator]=useState(false),[editingRoleId,setEditingRoleId]=useState(null);
 async function load(){setLoading(true);setError("");try{const [u,s,r,a]=await Promise.all([fetch("/api/admin/users"),fetch("/api/admin/staff"),fetch("/api/admin/roles"),fetch("/api/admin/user-subscriptions")]);const uj=await u.json(),sj=await s.json(),rj=await r.json(),aj=await a.json();if(!u.ok)throw Error(uj.error||"Erreur utilisateurs");if(!s.ok)throw Error(sj.error||"Erreur staff");if(!r.ok)throw Error(rj.error||"Erreur rôles");if(!a.ok)throw Error(aj.error||"Erreur abonnements utilisateurs");setUsers(uj.users||[]);setStaff(sj.staff||[]);setRoles(rj.roles||[]);setAssignments(aj.assignments||[]);setSubscriptions(aj.subscriptions||[]);}catch(e){setError(e.message||"Erreur réseau")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const staffMap=useMemo(()=>Object.fromEntries(staff.map(x=>[x.user_id,x])),[staff]);
 const subscriptionMap=useMemo(()=>Object.fromEntries(assignments.map(x=>[x.user_id,x])),[assignments]);
 const counts=useMemo(()=>({all:users.length,staff:staff.length,owners:staff.filter(x=>x.is_owner).length}),[users,staff]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return users.filter(u=>{const s=staffMap[u.user_id];const matches=filter==="all"||(filter==="users"&&!s)||(filter==="staff"&&!!s);const hay=[u.full_name,u.email,u.provider,...(s?.role_names||[])].filter(Boolean).join(" ").toLowerCase();return matches&&(!q||hay.includes(q))})},[users,staffMap,query,filter]);
 async function saveRoles(user,roleIds){setSaving(user.user_id);setError("");try{const r=await fetch("/api/admin/staff",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({user_id:user.user_id,role_ids:roleIds})});const j=await r.json();if(!r.ok)throw Error(j.error||"Impossible d'enregistrer");await load();setOpen(null)}catch(e){setError(e.message)}finally{setSaving("")}}
 async function remove(user){if(!confirm(`Retirer tous les accès staff de ${user.full_name||user.email} ?`))return;setSaving(user.user_id);try{const r=await fetch("/api/admin/staff",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({user_id:user.user_id})});const j=await r.json();if(!r.ok)throw Error(j.error||"Impossible");await load();setOpen(null)}catch(e){setError(e.message)}finally{setSaving("")}}
 async function saveSubscription(user,subscriptionId){setSaving(`sub:${user.user_id}`);setError("");try{const r=await fetch("/api/admin/user-subscriptions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({user_id:user.user_id,subscription_id:subscriptionId||null})});const j=await r.json();if(!r.ok)throw Error(j.error||"Impossible d’enregistrer l’abonnement");await load()}catch(e){setError(e.message)}finally{setSaving("")}}
 function beginCreate(){setEditingRoleId(null);setRoleForm(emptyRole);setShowRoleCreator(true)}
 function beginEditRole(r){setEditingRoleId(r.id);setRoleForm({name:r.name,description:r.description||"",permissions:Array.isArray(r.permissions)?r.permissions:[]});setShowRoleCreator(true)}
 async function saveRole(){setError("");if(!roleForm.name.trim())return setError("Donnez un nom au rôle.");try{const method=editingRoleId?"PATCH":"POST";const body=editingRoleId?{id:editingRoleId,...roleForm}:roleForm;const r=await fetch("/api/admin/roles",{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw Error(j.error||"Impossible d'enregistrer le rôle");setShowRoleCreator(false);setRoleForm(emptyRole);setEditingRoleId(null);await load()}catch(e){setError(e.message)}}
 async function deleteRole(r){if(r.is_system)return;if(!confirm(`Supprimer le rôle « ${r.name} » ? Les utilisateurs ne perdront que ce rôle.`))return;try{const res=await fetch("/api/admin/roles",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:r.id})});const j=await res.json();if(!res.ok)throw Error(j.error||"Impossible");await load()}catch(e){setError(e.message)}}
 const roleById=Object.fromEntries(roles.map(r=>[r.id,r]));
 const content=<>
  <div className="adminSectionHeading usersHeading"><div><span className="sectionTag">UTILISATEURS & ACCÈS</span><h2>Les comptes <span>Nexora.</span></h2><p>Créez vos propres rôles, choisissez leurs permissions et combinez plusieurs rôles sur un même compte.</p></div><div className="usersHeaderCount"><Users size={17}/><strong>{counts.all}</strong><span>comptes</span></div></div>
  <div className="accessHero"><div><ShieldCheck size={18}/><div><strong>Gestion des accès</strong><p>Chaque rôle peut avoir ses propres permissions. Un utilisateur peut cumuler plusieurs rôles : ses accès sont additionnés.</p></div></div><button className="primary" onClick={beginCreate}><Plus size={15}/> Nouveau rôle</button></div>
  <div className="userStats"><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}><Users size={15}/>Tous<strong>{counts.all}</strong></button><button className={filter==="staff"?"active":""} onClick={()=>setFilter("staff")}><ShieldCheck size={15}/>Staff<strong>{counts.staff}</strong></button><button className={filter==="users"?"active":""} onClick={()=>setFilter("users")}><UserRound size={15}/>Utilisateurs<strong>{counts.all-counts.staff}</strong></button><div className="roleCountBox"><strong>{roles.length}</strong><span>rôles configurés</span></div></div>
  {showRoleCreator&&<section className="roleBuilder"><div className="roleBuilderHead"><div><span className="sectionTag">CONFIGURATION DU RÔLE</span><h3>{editingRoleId?"Modifier le rôle":"Créer un nouveau rôle"}</h3></div><button className="iconButton" onClick={()=>setShowRoleCreator(false)}><X size={17}/></button></div><div className="roleBuilderGrid"><label>Nom du rôle<input value={roleForm.name} onChange={e=>setRoleForm({...roleForm,name:e.target.value})} placeholder="Ex. Modérateur Discord"/></label><label>Description<input value={roleForm.description} onChange={e=>setRoleForm({...roleForm,description:e.target.value})} placeholder="À quoi sert ce rôle ?"/></label></div><div className="permissionChooser"><div className="permissionChooserHead"><strong>Accès autorisés</strong><button type="button" onClick={()=>setRoleForm({...roleForm,permissions:roleForm.permissions.length===ACCESS.length?[]:ACCESS.map(x=>x[0])})}>{roleForm.permissions.length===ACCESS.length?"Tout retirer":"Tout sélectionner"}</button></div><div className="permissionGrid">{ACCESS.map(([key,label])=><label key={key} className={roleForm.permissions.includes(key)?"checked":""}><input type="checkbox" checked={roleForm.permissions.includes(key)} onChange={e=>setRoleForm({...roleForm,permissions:e.target.checked?[...roleForm.permissions,key]:roleForm.permissions.filter(p=>p!==key)})}/><span>{label}</span>{roleForm.permissions.includes(key)&&<Check size={13}/>}</label>)}</div></div><div className="roleBuilderActions"><button className="secondary" onClick={()=>setShowRoleCreator(false)}>Annuler</button><button className="primary" onClick={saveRole}><Save size={15}/>Enregistrer le rôle</button></div></section>}
  <div className="rolesSection"><div className="rolesSectionHead"><div><span className="sectionTag">RÔLES</span><h3>Profils d'accès</h3></div><span>{roles.length} rôle{roles.length>1?"s":""}</span></div><div className="rolesGrid">{roles.map((r,i)=><article className={`roleConfigCard ${tones[i%tones.length]}`} key={r.id}><div className="roleConfigTop"><div className="roleConfigIcon"><ShieldCheck size={16}/></div><div><h4>{r.name}</h4><p>{r.description||"Aucune description"}</p></div>{r.is_system&&<em>SYSTÈME</em>}</div><div className="rolePermissionList">{r.permissions?.includes("all")?<span className="permissionAll">Accès total</span>:(r.permissions||[]).slice(0,4).map(p=><span key={p}>{ACCESS.find(a=>a[0]===p)?.[1]||p}</span>)}{!r.permissions?.includes("all")&&(r.permissions||[]).length>4&&<span>+{r.permissions.length-4}</span>}</div><div className="roleConfigActions"><button onClick={()=>beginEditRole(r)}><Pencil size={13}/> Modifier</button>{!r.is_system&&<button className="dangerText" onClick={()=>deleteRole(r)}><Trash2 size={13}/> Supprimer</button>}</div></article>)}</div></div>
  <div className="usersToolbar"><label className="usersSearch"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher un nom, une adresse e-mail ou un rôle…"/></label><span>{filtered.length} résultat{filtered.length>1?"s":""}</span></div>
  {error&&<p className="authError">{error}</p>}
  {loading?<div className="adminEmpty"><LoaderCircle className="spin"/> Chargement des comptes…</div>:filtered.length===0?<div className="emptyState"><UserRound size={30}/><h2>Aucun compte trouvé</h2><p>Modifiez votre recherche ou votre filtre.</p></div>:<div className="usersGrid">{filtered.map(u=>{const s=staffMap[u.user_id];const selected=s?.role_ids||[];const sub=subscriptionMap[u.user_id];const isOpen=open===u.user_id;return <article className={`userCard staffUser ${isOpen?"expanded":""}`} key={u.user_id}><div className="userAvatar"><Users size={19}/></div><div className="userMain"><div className="userNameLine"><h2>{u.full_name||u.email?.split("@")[0]||"Utilisateur"}</h2>{s?.is_owner?<span className="rolePill owner"><ShieldCheck size={11}/>Propriétaire</span>:s?.role_names?.length?<div className="rolePills">{s.role_names.map(n=><span className="rolePill" key={n}>{n}</span>)}</div>:<span className="rolePill user"><UserRound size={11}/>Utilisateur</span>}{sub&&<span className={`subscriptionUserBadge ${sub.subscription_slug||""}`}>✦ {sub.subscription_name}</span>}</div><p>{u.email}</p><span>{u.provider||"email"} · inscrit le {new Date(u.created_at).toLocaleDateString("fr-FR")}</span></div><div className="staffControls">{s?.is_owner?<b className="adminBadge"><ShieldCheck size={13}/> PROPRIÉTAIRE</b>:<><button className="primary small" onClick={()=>setOpen(isOpen?null:u.user_id)}>{s?"Gérer les accès":"Ajouter au staff"}</button>{s&&<button className="dangerButton" onClick={()=>remove(u)} disabled={saving===u.user_id}><Trash2 size={14}/>Retirer</button>}</>}</div><button type="button" className="userDetailsToggle" onClick={()=>setOpen(isOpen?null:u.user_id)}>{isOpen?"Masquer la configuration":s?"Configurer les rôles et accès":"Choisir les rôles"}</button>{isOpen&&<><RoleAssignPanel roles={roles} selected={selected} onSave={(ids)=>saveRoles(u,ids)} saving={saving===u.user_id}/><SubscriptionAssignPanel subscriptions={subscriptions} selected={sub?.subscription_id||""} onSave={(id)=>saveSubscription(u,id)} saving={saving===`sub:${u.user_id}`}/></>}</article>})}</div>}
 </>;
 if(embedded)return <div className="adminSubpage">{content}</div>;
 return <main className="adminPage"><header className="adminTop"><div><span className="sectionTag">NEXORA ADMIN</span><h1>Utilisateurs <span>& accès.</span></h1><p>Gérez les membres, les rôles et toutes leurs permissions.</p></div><div className="adminActions"><Link href="/" className="secondary">Voir le site</Link><button className="secondary" onClick={async()=>{await createClient().auth.signOut();location.href="/admin/connexion"}}><LogOut size={15}/>Déconnexion</button></div></header><section className="adminWrap"><AdminControlNav active="users" />{content}</section></main>;
}

function SubscriptionAssignPanel({subscriptions,selected,onSave,saving}){return <div className="subscriptionAssignPanel"><div><strong>Abonnement du compte</strong><small>Attribuez une des deux formules à cet utilisateur. Le badge apparaîtra aussi sur son profil.</small></div><div className="subscriptionAssignRow"><select value={selected||""} onChange={e=>onSave(e.target.value)} disabled={saving}>{<option value="">Aucun abonnement</option>}{subscriptions.map(p=><option key={p.id} value={p.id}>{p.name}{p.price!=null?` — ${Number(p.price).toFixed(2).replace(".",",")} € / ${p.billing_period||"mois"}`:""}</option>)}</select>{saving&&<span>Enregistrement…</span>}</div>{selected&&<div className="subscriptionAssignHint">✦ Badge actif : {subscriptions.find(p=>String(p.id)===String(selected))?.name||"Abonnement"}</div>}</div>}

function RoleAssignPanel({roles,selected,onSave,saving}){const [ids,setIds]=useState(selected||[]);const active=roles.filter(r=>ids.includes(r.id));return <div className="roleAssignPanel"><div className="roleAssignHead"><div><strong>Rôles de cet utilisateur</strong><small>Plusieurs rôles peuvent être sélectionnés. Les permissions se cumulent.</small></div><span>{ids.length} sélectionné{ids.length>1?"s":""}</span></div><div className="roleSelectGrid">{roles.map(r=><label key={r.id} className={ids.includes(r.id)?"selected":""}><input type="checkbox" checked={ids.includes(r.id)} onChange={e=>setIds(e.target.checked?[...ids,r.id]:ids.filter(x=>x!==r.id))}/><div><b>{r.name}</b><small>{r.description||""}</small></div><span>{r.permissions?.includes("all")?"TOTAL":`${r.permissions?.length||0} accès`}</span></label>)}</div><div className="combinedAccess"><strong>Accès résultants</strong><div>{Array.from(new Set(active.flatMap(r=>r.permissions||[]))).map(p=><span key={p}>{p==="all"?"Accès total":ACCESS.find(a=>a[0]===p)?.[1]||p}</span>)}</div></div><div className="roleAssignActions"><button className="secondary" onClick={()=>setIds(selected||[])}>Réinitialiser</button><button className="primary" disabled={!ids.length||saving} onClick={()=>onSave(ids)}><Save size={14}/>{saving?"Enregistrement…":"Enregistrer les accès"}</button></div></div>}
