import Link from "next/link";
import {BookOpen,MessageSquare,UserRound,ArrowUpRight,LogOut,Settings2,PanelLeft,ShieldCheck} from "lucide-react";
import {createClient} from "../../lib/supabase/server"; import {redirect} from "next/navigation"; import Header from "../ui/Header"; import Footer from "../ui/Footer";
export const metadata={title:"Mon espace"};
export default async function Compte(){const supabase=await createClient();const {data:claimsData}=await supabase.auth.getClaims();if(!claimsData?.claims)redirect("/connexion");const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/connexion");const {data:admin}=await supabase.from("admin_users").select("user_id").eq("user_id",user.id).maybeSingle();const isAdmin=!!admin;const name=user.user_metadata?.full_name||user.email?.split("@")[0]||"Membre Nexora";
return <main><Header/><section className="subPage"><div className="subHero"><span className="sectionTag">ESPACE CLIENT</span><h1>Bonjour,<br/><span>{name}.</span></h1><p className="lead">Votre espace Nexora est connecté à votre compte. Retrouvez vos formations, vos demandes et vos informations.</p><div className="accountBar"><div><span>COMPTE CONNECTÉ</span><strong>{user.email}</strong></div><form action="/api/auth/logout" method="post"><button className="secondary" type="submit"><LogOut size={15}/> Se déconnecter</button></form></div>
<div className="dashboardGrid"><Dash icon={<BookOpen/>} tag="FORMATIONS" title="Mes formations" text="Retrouvez vos formations et votre progression." href="/formations" label="Découvrir"/><Dash icon={<MessageSquare/>} tag="DEMANDES" title="Mes demandes" text="Suivez vos demandes et échangez avec Nexora." href="/demandes" label="Voir mes demandes"/><Dash icon={<UserRound/>} tag="PROFIL" title="Mes informations" text="Modifiez les informations de votre compte." href="/profil" label="Modifier"/></div>
{isAdmin&&<><div className="adminAccountHeader"><ShieldCheck size={17}/><div><span>ADMINISTRATEUR NEXORA</span><strong>Outils de gestion privés</strong></div></div><div className="dashboardGrid adminDashboardGrid"><Dash icon={<PanelLeft/>} tag="ADMIN" title="Panneau de contrôle" text="Gérez le catalogue, l’éditeur du site, les utilisateurs, le staff et les demandes depuis un seul espace." href="/admin" label="Ouvrir le panneau" admin/></div></>}
</div></section><Footer/></main>}
function Dash({icon,tag,title,text,href,label,admin}){return <article className={`dashCard ${admin?"adminDashCard":""}`}><div className="dashIcon">{icon}</div><span>{tag}</span><h2>{title}</h2><p>{text}</p><Link href={href}>{label}<ArrowUpRight size={15}/></Link></article>}
